name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: android-actions/setup-android@v2

      - run: chmod +x ./GiftcardSite/gradlew

      - run: ./gradlew build
        working-directory: ./GiftcardSite